id = "aml"
name = "AML"
version = "0.2.1"
schema_version = 1
authors = ["Christopher Choi <christopher@arkenstone-labs.com>"]
description = "AML and Octra AppliedML support through amlc-lsp."
repository = "https://github.com/arkenstone-lab/amlc-lsp"

[language_servers.amlc-lsp]
name = "AMLC Language Server"
language = "AML"

[language_servers.amlc-lsp.language_ids]
AML = "aml"

[grammars.aml]
repository = "https://github.com/arkenstone-lab/amlc-lsp"
commit = "9c9774600f9966a739bbc08a53a0e73a1ea213ac"
