id = "aml"
name = "AppliedML"
version = "0.3.0"
schema_version = 1
authors = ["Christopher Choi <christopher@arkenstone-labs.com>"]
description = "Applied Meta Language (AppliedML) support through amlc-lsp."
repository = "https://github.com/arkenstone-lab/amlc-lsp"

[language_servers.amlc-lsp]
name = "AMLC Language Server"
language = "AppliedML"

[language_servers.amlc-lsp.language_ids]
AppliedML = "aml"

[grammars.aml]
repository = "https://github.com/arkenstone-lab/amlc-lsp"
commit = "9c9774600f9966a739bbc08a53a0e73a1ea213ac"
